linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker

matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

install:
  #- chmod +x .travis/install.sh
  #- ./.travis/install.sh

script:
  #  - chmod +x .travis/run.sh
  #  - ./.travis/run.sh
  - docker run -i ubuntu:xenial bash < travis/build_on_xenial_docker.sh
