#branches:
#  only:
#  - master
#  - polymorph

language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: g++
      sudo: required
    - os: osx
    - os: windows

before_install:
    - eval "${MATRIX_EVAL}"
    - g++ --version

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis/install_osx.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis/install_linux.sh ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install qt5-default ; fi

script:
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis/script_osx.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis/script_linux.sh ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then travis/script_windows.sh ; fi
    #  - qmake
    #  - make
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then macdeployqt MrWriter.app -dmg ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl --upload-file MrWriter.dmg https://transfer.sh/MrWriter.dmg ; fi
