linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker

matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
      - <<: *windows

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run -i ubuntu:xenial bash < travis/build_on_xenial_docker.sh ; fi




