= MrWriter

image:https://badges.gitter.im/unruhschuh/MrWriter.svg[link="https://gitter.im/unruhschuh/MrWriter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"] image:https://travis-ci.com/unruhschuh/MrWriter.svg?branch=master["Build Status", link="https://travis-ci.com/unruhschuh/MrWriter"] image:https://ci.appveyor.com/api/projects/status/09p26mck1aa1fbha?svg=true["Build Status", link="https://ci.appveyor.com/project/unruhschuh/mrwriter"]

== About
Notetaking and blackboard replacement application. Inspired by Xournal. Written in C++/Qt for Linux / Windows / Mac.

See the http://unruhschuh.github.io/MrWriter/[project homepage] for more informations and screenshots.

https://tooomm.github.io/github-release-stats/?username=unruhschuh&repository=MrWriter[Release stats]

== Build
=== Without conan
* Download and install http://www.qt.io/download/[Qt]
* Run in the terminal
** `git clone https://github.com/unruhschuh/MrWriter.git`
** `cd MrWriter`
** `mkdir build`
** `cd build`
** `cmake ..`
** `cmake --build .`

=== With conan
* Download and install http://www.conan.io[conan]
* Run in the terminal
** `git clone https://github.com/unruhschuh/MrWriter.git`
** `cd MrWriter`
** `mkdir build`
** `cd build`
** `conan install ..`
** `cmake ..`
** `cmake --build .`

== The latest and greatest
For testing purposes you may download the latests build by clicking on one of the "build passing" buttons.
There you'll find the build logs.
At the bottom there is a url of the form `https://transfer.sh/342Xasf/XXX.Y` where `Y` is either zip/dmg/AppImage depending on the platforms Windows / Mac / Linux.
Copy that and paste it into your browser's url field or use `wget` in the command line.

== Known issues
=== Fonts fail to load on Ubuntu with the AppImage
This seems to be an issue with Qt in conan. As a workaround, run the AppImage using `FONTCONFIG_PATH=/etc/fonts ./MrWriter-b71ccd2-x86_64.AppImage`.
